"""nevers

Revision ID: 4640c1f25d4d
Revises: d92c4e9ba1c3
Create Date: 2023-04-15 19:11:15.005566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4640c1f25d4d'
down_revision = 'd92c4e9ba1c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
