"""nevers

Revision ID: 712a1824a99b
Revises: 
Create Date: 2023-04-15 15:26:27.163531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712a1824a99b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
