"""nevers

Revision ID: 8ae60773f8ba
Revises: dfff05de9be2
Create Date: 2023-04-15 19:19:35.229907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae60773f8ba'
down_revision = 'dfff05de9be2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
