"""nevers

Revision ID: d92c4e9ba1c3
Revises: e231d0b9758a
Create Date: 2023-04-15 19:09:44.987886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92c4e9ba1c3'
down_revision = 'e231d0b9758a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
