"""nevers

Revision ID: dfff05de9be2
Revises: 4640c1f25d4d
Create Date: 2023-04-15 19:17:39.670749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfff05de9be2'
down_revision = '4640c1f25d4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
