"""nevers

Revision ID: e231d0b9758a
Revises: 712a1824a99b
Create Date: 2023-04-15 17:20:07.884249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e231d0b9758a'
down_revision = '712a1824a99b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
